@startuml DUC_FitPass

title Diagrama de Casos de Uso - Sistema FitPass Gym Management

actor "Usuário" as user
actor "Administrador" as admin
actor "Funcionário" as staff
actor "Sistema" as system

rectangle "Sistema FitPass" {
  usecase "Cadastro de Usuário" as UC1
  usecase "Login do Usuário" as UC2
  usecase "Agendamento de Aulas" as UC3
  usecase "Cancelamento de Aulas" as UC4
  usecase "Consulta de Resultados" as UC5
  usecase "Atualização de Perfil" as UC6
  usecase "Pagamento de Mensalidade" as UC7
  usecase "Cadastro de Funcionário" as UC8
  usecase "Alteração de Cadastro de Funcionário" as UC9
  usecase "Relatório de Atendimento" as UC10
  usecase "Cadastro de Equipamento" as UC11
  usecase "Atualização de Equipamento" as UC12
  usecase "Controle de Acesso ao Centro" as UC13
  usecase "Avaliação Física" as UC14
  usecase "Criação de Planos de Treino" as UC15
  usecase "Gerenciamento de Feedbacks" as UC16
  usecase "Envio de Notificações" as UC17
  usecase "Gestão de Promoções" as UC18
  usecase "Relatório de Finanças" as UC19
  usecase "Acesso a Suporte" as UC20
}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5
user --> UC6
user --> UC7
user --> UC20

admin --> UC8
admin --> UC9
admin --> UC10
admin --> UC11
admin --> UC12
admin --> UC18
admin --> UC19

staff --> UC13
staff --> UC14
staff --> UC15
staff --> UC16

system --> UC17

UC2 ..> UC3 : inclui
UC2 ..> UC5 : inclui
UC2 ..> UC6 : inclui
UC2 ..> UC7 : inclui

@enduml